f = open("profile.wxml", encoding="utf-8")
c = f.read()
f.close()
c = c.replace("recordCount or 0", "recordCount || 0")
c = c.replace("reportCount or 0", "reportCount || 0")
f = open("profile.wxml", "w", encoding="utf-8")
f.write(c)
f.close()
print("Fixed")
